name: project-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - numpy
  - protobuf
  - easydict
  - pytorch
  - pillow
  - matplotlib
  - wxpython
  - shapely
  - tqdm
  - pip:
    - open3d
    - opencv-python
